/**
 * @file    DMX.h
 * @author Hanspeter Hochreutener, hhrt@zhaw.ch
 * @modified_by Patrick Rennhard, renn@zhaw.ch
 * @modified_date 12.08.2025
 * @version 1.0
 * @brief DMX output to LED party panel
 *
 * @note For the linker to find the UART functions it is necessary to uncomment this line:
 * @n <b>\#define HAL_UART_MODULE_ENABLED</b>
 * @n in the file <b>stm32f4xx_hal_conf.h</b>
 * @n otherwise there is this linker error: <b>undefined reference to `HAL_UART_Init'</b>
 *
 * Further DMX channels could be added by increasing DMX_COUNT
 */

#ifndef DMX_H_
#define DMX_H_

#include "arm_math.h"

/******************************************************************************
 * Includes
 *****************************************************************************/

/******************************************************************************
 * Defines
 *****************************************************************************/
#define DMX_CHANNEL_COUNT	8				///< Number of DMX channels
#define DMX_CHANNEL_OFFSET 5

/******************************************************************************
 * Variables
 *****************************************************************************/
extern uint8_t DMX_data[DMX_CHANNEL_COUNT + 1];

/******************************************************************************
 * Functions
 *****************************************************************************/

/** ***************************************************************************
 * @brief Configure GPIO for DMX output of lightorgan and the UART
 *
 * Transmit	= GPIO PC12 = UART5_TX
 * @n See DMX_transmit() for details about generating the BREAK
 *****************************************************************************/
void DMX_init(void);

/** ***************************************************************************
 * @brief Set the RGB color in the DMX data buffer
 * @param red Red value (0..255)
 * @param green Green value (0..255)
 * @param blue Blue value (0..255)
 * @param white White value (0..255)
 *****************************************************************************/
void DMX_setColor(uint8_t red, uint8_t green, uint8_t blue, uint8_t white);

/** ***************************************************************************
 * @brief Transmit the DMX data
 *
 * https://en.wikipedia.org/wiki/DMX512#/media/File:Annotated_trace_of_DMX-512_signal.png
 * @note The DMX signal is generated by a UART
 * @note However,
 * the BREAK and MAB signals of the DMX protocol can not be generated by a UART.
 * @note This workaround is used:
 * - Disconnect TX pin from the UART output (= reset the alternate function)
 * - Configure TX pin as normal output
 * - Set it to low and wait 100us = BREAK
 * - Set it to hogh and wait 12us = BREAK
 * - Disconnect TX pin as normal output (= reset normal output function)
 * - Configure TX pin to use the UART output (= alternate function)
 *
 * The use the UART to transmit the data.
 *****************************************************************************/
void DMX_transmit(void);

#endif
